# This file was generated by GoReleaser. DO NOT EDIT.
class Daydeal < Formula
  desc "CLI tool to fetch the current DayDeal"
  homepage "https://github.com/mhutter/daydeal"
  url "https://github.com/mhutter/daydeal/releases/download/v1.0.2/daydeal_1.0.2_Darwin_x86_64.tar.gz"
  version "1.0.2"
  sha256 "92bf857a5e669bba142fbaa8baa7fee640920435fba5d48fc333f6bdee640d33"

  def install
    bin.install "daydeal"
  end

  test do
    system "#{bin}/daydeal"
  end
end
