# This file was generated by GoReleaser. DO NOT EDIT.
class GitBrowse < Formula
  desc "Open the current repository in the browser."
  homepage "https://github.com/mhutter/git-browse"
  url "https://github.com/mhutter/git-browse/releases/download/v1.0.0/git-browse_1.0.0_Darwin_x86_64.tar.gz"
  version "1.0.0"
  sha256 "b02c6afc45a6ff6c1c606539b4ed612b7c91057d719a268f745e63a05386c01b"

  def install
    bin.install "git-browse"
  end

  test do
    system "#{bin}/git-browse"
  end
end
