# This file was generated by GoReleaser. DO NOT EDIT.
class Issues < Formula
  desc "Show all open GitHub issues for the current repository."
  homepage "https://github.com/mhutter/issues"
  url "https://github.com/mhutter/issues/releases/download/v1.0.0/issues_1.0.0_Darwin_x86_64.tar.gz"
  version "1.0.0"
  sha256 "6f2487caf2dd74d2f1a9df9df71784615bf51529943ed07bfb42d9fd4f731fda"

  def install
    bin.install "issues"
  end

  test do
    system "#{bin}/issues"
  end
end
