# This file was generated by GoReleaser. DO NOT EDIT.
class Keygen < Formula
  desc "CLI tool to genereate base64-encoded AES keys"
  homepage "https://github.com/mhutter/keygen"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/mhutter/keygen/releases/download/v1.0.0/keygen_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "f4298310842b4ab8ae933b9b1b4a6f11caec30016536a85f4f94cde1a2f12734"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/mhutter/keygen/releases/download/v1.0.0/keygen_1.0.0_Linux_x86_64.tar.gz"
      sha256 "86c5bc2bd970274aa38b34e9483fd7137caa69dfca0a40a39b2ac98b6d1a2bb8"
    end
  end

  def install
    bin.install "keygen"
  end

  test do
    system "#{bin}/keygen 1 | grep -q '..=='"
  end
end
