# This file was generated by GoReleaser. DO NOT EDIT.
class LatestRelease < Formula
  desc "Check the latest release of a GitHub repository"
  homepage "https://github.com/mhutter/latest-release"
  url "https://github.com/mhutter/latest-release/releases/download/v1.0.0/latest-release_1.0.0_Darwin_x86_64.tar.gz"
  version "1.0.0"
  sha256 "c102af2d2a75fb12929105ade8610f0b0418a32e3fa5332257611d3e6c721212"

  def install
    bin.install "latest-release"
  end

  test do
    system "#{bin}/latest-release -v"
  end
end
