# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbb < Formula
  desc "CLI for the SBB timetables"
  homepage "https://github.com/mhutter/sbb"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhutter/sbb/releases/download/v1.2.0/sbb_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "bc3ff726e644c1626c0d32e9d07b6889ee9159f8f03dda4892203f54778668b8"
    end
    if Hardware::CPU.arm?
      url "https://github.com/mhutter/sbb/releases/download/v1.2.0/sbb_1.2.0_Darwin_arm64.tar.gz"
      sha256 "14a36e4efdaad1b416d4f245ff30b5c8226a3f85d81c3ebecc96871e8f7aafb5"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhutter/sbb/releases/download/v1.2.0/sbb_1.2.0_Linux_x86_64.tar.gz"
      sha256 "7960ffd109f417c7384a93c9e45a2e3871c771f49562c3790d1a9f07bd857b7d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mhutter/sbb/releases/download/v1.2.0/sbb_1.2.0_Linux_arm64.tar.gz"
      sha256 "50c4594629f9259afde81913d27666874ace0a2bcbf864cbea6594a97065a9c7"
    end
  end

  def install
    bin.install "sbb"
  end

  test do
    system "#{bin}/sbb"
  end
end
