# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbb < Formula
  desc "CLI for the SBB timetables"
  homepage "https://github.com/mhutter/sbb"
  version "1.1.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mhutter/sbb/releases/download/v1.1.1/sbb_1.1.1_Darwin_x86_64.tar.gz"
      sha256 "7523bcb34aad42bedeaefad39717b637dcdf4683406f9145c6116362db523d6f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/mhutter/sbb/releases/download/v1.1.1/sbb_1.1.1_Darwin_arm64.tar.gz"
      sha256 "a3811ad03c8194bc05dffeb8fb49ec33e001e84fa0832eea7e97bdf8da86989a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mhutter/sbb/releases/download/v1.1.1/sbb_1.1.1_Linux_x86_64.tar.gz"
      sha256 "b373736b2f80b5e4f58d0cbb8a45146ee603f73ecef085152b4dff88df2a4280"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mhutter/sbb/releases/download/v1.1.1/sbb_1.1.1_Linux_arm64.tar.gz"
      sha256 "5df9ff6c9b61865f4fd66edf6b1873872927595a68546db74a2b44cc3c1125c8"
    end
  end

  def install
    bin.install "sbb"
  end

  test do
    system "#{bin}/sbb"
  end
end
