# This file was generated by GoReleaser. DO NOT EDIT.
class Uuid < Formula
  desc "CLI tool to generate random UUIDs"
  homepage "https://github.com/mhutter/uuid"
  url "https://github.com/mhutter/uuid/releases/download/v1.0.0/uuid_1.0.0_Darwin_x86_64.tar.gz"
  version "1.0.0"
  sha256 "5f36c586842a666bd99aaae24665ca30aa6bc71add7b7b11529168cd79b99bc5"

  def install
    bin.install "uuid"
  end

  test do
    system "#{bin}/uuid"
  end
end
